server:
  port: 8080


spring:
  profiles:
      active: local
  datasource:
    url: jdbc:log4jdbc:mysql://121.137.131.159:3306/reservation_dev?useUnicode=true&autoReconnect=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sansu_dev
    password: sansu!123
    initialize: false
    platform: all
  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: create
      ddl-auto: validate
      debug: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    jdbc: OFF
    jdbc.sqltiming: DEBUG
    jdbc.resultsettable: DEBUG
