server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://121.137.131.159:3306/reservation_dev?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    username: sansu_dev
    password: sansu!123
    initialize: false
    platform: all
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    jdbc: OFF
    jdbc.sqltiming: DEBUG
    jdbc.resultsettable: DEBUG