server:
  port: 8080

spring:
  profiles:
    active: prd
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/sansuok2?useUnicode=true&autoReconnect=true
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sansuok2
    password: "storyerp79!"
    initialize: false
    platform: all
    tomcat:
      test-while-idle: true
      time-between-eviction-runs-millis: 3600000
      min-evictable-idle-time-millis: 7200000
      test-on-borrow: true
      validation-query: select 1
      max-active: 10
      initial-size: 2
      max-idle: 2
      min-idle: 1
  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: validate
      debug: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    jdbc: OFF
    jdbc.sqltiming: DEBUG
    jdbc.resultsettable: DEBUG